name: The Glass Menagerie
favicon: null
layout_spectrum: 0.8537554231006652
typography_spectrum: 0.22734132269397378
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.1876728148199618
  lightness: 0.7138341560494155
  saturation: 0.25167194358073175
  rhythmicContrast: 0.6840213101822883
purpose: []
